'\" t
.\"
.TH "MERITOUS" "6" "February 3, 2008" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
meritous \- an action adventure dungeon\-crawl game
.SH "SYNOPSIS"
.HP \w'\fBmeritous\fR\ 'u
\fBmeritous\fR [\fBfullscreen\fR]
.SH "DESCRIPTION"
.PP
Meritous is an action\-adventure dungeon\-crawl game where you play the role of a character with a PSI circuit, capable of destroying monsters in a radius around the player\&.
.PP
This manual page was written for the
Debian
distribution because the original program does not have a manual page\&.
.SH "BASIC CONTROLS"
.PP
The following the basic controls to the game:
.PP
\fBArrow keys\fR
.RS 4
Move around\&. To walk through doors, simply walk up to them and push against them\&.
.RE
.PP
\fBSpace\fR
.RS 4
Charge your PSI circuit for attack, release to attack\&.
.RE
.PP
\fBEscape\fR
.RS 4
Exit the game\&.
.RE
.PP
\fBH\fR
.RS 4
View the help file\&.
.RE
.PP
\fBTab\fR
.RS 4
View the map (you can use the arrow keys to scroll around the map, press space to move quickly in the map)\&.
.RE
.PP
\fBEnter\fR
.RS 4
Activate a trigger tile that you are standing on\&. Enter is also used for various other things, such as reading in\-game dialog\&.
.RE
.PP
\fBP\fR
.RS 4
Pause the game\&.
.RE
.SH "OPTIONS"
.PP
These programs do not follow the usual
GNU
command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. Instead, just type the command after the executable name\&.
.PP
\fBfullscreen\fR
.RS 4
Runs the game in full screen mode\&.
.RE
.SH "AUTHOR"
.PP
This manual page was written by D\&. Moonfire
<contact@mfgames\&.com>
for the
Debian
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2008 D. Moonfire
.br
